// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyDpSy3zVZAQkoE1RE4HoKz-G9uADcG-SwU',
//     appId: '1:621926305288:web:a756fae6e9dac3b9b8cbbd',
//     messagingSenderId: '621926305288',
//     projectId: 'ajwaae-9dd49',
//     authDomain: 'ajwaae-9dd49.firebaseapp.com',
//     storageBucket: 'ajwaae-9dd49.appspot.com',
//     measurementId: 'G-ZH9ZXCVW5X',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyD8_KM_GVgCX2DJBbji7F4UrMnI5qnsWOY',
//     appId: '1:621926305288:android:948e75c1a2567d4cb8cbbd',
//     messagingSenderId: '621926305288',
//     projectId: 'ajwaae-9dd49',
//     storageBucket: 'ajwaae-9dd49.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyAo3vtzUmpbz3c0T0osBwUnhoQXp8BPJLM',
//     appId: '1:621926305288:ios:ee2839038c4a5466b8cbbd',
//     messagingSenderId: '621926305288',
//     projectId: 'ajwaae-9dd49',
//     storageBucket: 'ajwaae-9dd49.appspot.com',
//     iosClientId:
//         '621926305288-f3s4qhg7fnev85q10u2sq96jt38sgm83.apps.googleusercontent.com',
//     iosBundleId: 'com.happiness_club_merchant.app',
//   );
// }
